### ISSUE TITLE
Flink仓库分析报错文件名或扩展名太长

### ISSUE THREAD

**Issue by rc452860** [inherd/coco#97]
### Describe the bug
Flink仓库分析报错文件名或扩展名太长。

### Steps to reproduce (please include code)
执行步骤: 
```
PS C:\Users\ovo\Documents\workspace\report\git> .\coco-windows.exe
target dir: ".coco\\github.com\\apache\\spark"
target dir: ".coco\\github.com\\apache\\flink"
thread '<unnamed>' panicked at 'failed to clone: failed to stat 'C:/Users/ovo/Documents/workspace/report/git/.coco/github.com/apache/flink/flink-connectors/flink-connector-files/src/test/resources/bucket-state-migration-test/full-no-in-progress-v1-template/bucket/test-bucket/.part-0-0.inprogress.a88d5993-77bc-44ce-880b-9f2a43b59ab4': 文件名或扩展名太长。
; class=Os (2); code=Exists (-4)', src\infrastructure\git\git_repository.rs:35:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

配置文件: 
```
---
repos: 
  - url: https://github.com/apache/spark
  - url: https://github.com/apache/flink
    languages: [Java,Scale]
```

### Environment
- coco version 0.5.4
- Rust version unknow
- OS: [Windows 10]
